### ISSUE TITLE
Deploying this node cause node-red  to stop working

### ISSUE THREAD

**Issue by eduardo-vela** [bmdevx/node-red-contrib-ecowitt-gateway#1]
I tried to install this node-red to get data from my ecowitt,  but it caused to crash my installation of red-node. I think there is some missing validations to handle errors in the design of the node.

**Comment by bmdevx** [comment]
Would you be able to post the log file and node configuration from your NodeRED instance that contains the crash information?

**Comment by FlorianDessloch** [comment]
`21 May 09:47:48 - [red] Uncaught Exception:
21 May 09:47:48 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Unknown Field Type".
`

That's the error I get as soon as I send a msg with a timestamp as payload,
next node red restarts.
This happens in an otherwise empty environment, just an inject, a debug and your LiveData.
Could you please document, what kind of payload s expected. maybe provide an example?

**Comment by bmdevx** [comment]
The node should accept any payload even if it is null/undefined. Can you tell me what version firmware your Ecowitt 1000/2000 is using. If it is below 1.6.4 try disabling "Include Rain Data" or upgrading your firmware.

**Comment by FlorianDessloch** [comment]
I have a GW1100 with 2.3.2 firmware.
I just checked your npm page. It says, there is a dependancy on ecowitt-gateway.
I installed it in my test Docker container, but the restart still occurs.
I assume faulty or no data coming back wouldn't crash nodered.
BTW I'm running nodered v3.1.9

**Comment by bmdevx** [comment]
What is the weather station you are running? Also if you can please run the following code with the [ecowitt-gateway](https://www.npmjs.com/package/ecowitt-gateway) package and post the output. It should let me debug the parsing function with the data you are receiving.

```js
const EWG = require('ecowitt-gateway');
const gw = EWG('REPLACE with IPADDRESS of GATEWAY');

gw.runCommand(0x27)
	.then(buffer => {
         console.log(`CMD_LD: ${buffer.toString('hex').toUpperCase()}\n`);
     });

gw.runCommand(0x34)
	.then(buffer => {
         console.log(`CMD_R_RD: ${buffer.toString('hex').toUpperCase()}\n`);
     });

gw.runCommand(0x57)
	.then(buffer => {
         console.log(`CMD_R_R: ${buffer.toString('hex').toUpperCase()}\n`);
     });
```
